-- Apaga e recria o banco
DROP DATABASE IF EXISTS expcriativa;
CREATE DATABASE expcriativa;
USE expcriativa;

-- Usuários
CREATE TABLE USUARIO (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    FOTOPERFIL BLOB,
    NOME VARCHAR(50),
    CPF VARCHAR(16),
    DT_NASCIMENTO DATE,
    TELEFONE VARCHAR(20),
    EMAIL VARCHAR(50),
    SENHA VARCHAR(255)
);

-- Banners
CREATE TABLE BANNER (
    ID_BANNER INT AUTO_INCREMENT PRIMARY KEY,
    IMAGEM LONGBLOB
);

-- Categorias de produtos
CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50)
);

-- Produtos
CREATE TABLE PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50),
    VALOR INT,
    FK_CATEGORIA INT,
    IMAGEM LONGBLOB,
    FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA) ON DELETE CASCADE
);

-- Pedidos finalizados
CREATE TABLE PEDIDO (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_PEDIDO DATE,
    FK_ID_CLIENTE INT,
    FOREIGN KEY (FK_ID_CLIENTE) REFERENCES USUARIO(ID_CLIENTE) ON DELETE CASCADE
);

-- Carrinho de compras (temporário)
CREATE TABLE PROD_PEDIDO (
    ID_PROD_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    FK_ID_PRODUTO INT,
    FK_ID_CLIENTE INT,
    QUANTIDADE INT,
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_CLIENTE) REFERENCES USUARIO(ID_CLIENTE) ON DELETE CASCADE
);

-- Itens congelados no momento da finalização do pedido
CREATE TABLE ITEM_PEDIDO (
    ID_ITEM INT AUTO_INCREMENT PRIMARY KEY,
    FK_ID_PEDIDO INT,
    FK_ID_PRODUTO INT,
    QUANTIDADE INT,
    FOREIGN KEY (FK_ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO) ON DELETE CASCADE
);

-- Inserção de categorias padrão
INSERT INTO CATEGORIA (NOME)
VALUES 
    ("Gloss"),
    ("Body Splash"),
    ("Hidratante"),
    ("Maquiagem"),
    ("Perfume"),
    ("Skincare");

INSERT INTO USUARIO (NOME, CPF, DT_NASCIMENTO, TELEFONE, EMAIL, SENHA) VALUES ('adm', '1', '2005-01-12', '1', 'adm@adm', MD5('123') );

-- Inserção de produtos na tabela PRODUTO
-- Categoria: Maquiagem (ID 4)
INSERT INTO PRODUTO (NOME, VALOR, FK_CATEGORIA, IMAGEM) VALUES 
('PALETA KYLIE JENNER', 399, 4, NULL),
('BASE DIOR', 415, 4, NULL),
('BLUSH BENEFIT', 139, 4, NULL),
('RIMEL YSL', 269, 4, NULL);

-- Categoria: Body Splash (ID 2)
INSERT INTO PRODUTO (NOME, VALOR, FK_CATEGORIA, IMAGEM) VALUES 
('BODYSPLASH VS AQUA KISS', 169, 2, NULL),
('BODYSPLASH BATH AND BODY WORKS', 159, 2, NULL),
('BODYSPLASH CH 212 HEROES FOR HER', 269, 2, NULL),
('BODYSPLASH LIGHT BLUE', 269, 2, NULL);

-- Categoria: Gloss (ID 1)
INSERT INTO PRODUTO (NOME, VALOR, FK_CATEGORIA, IMAGEM) VALUES 
('GLOSS ADDICT MAXIMIZER DIOR', 265, 1, NULL),
('YSL LOVE SHINE CANDY GLAZE', 269, 1, NULL),
('RHODE TINT LABIAL RESPBERRY JELLY', 229, 1, NULL),
('DIOR LIP GLOW OIL PINK', 265, 1, NULL);

-- Categoria: Skincare (ID 6)
INSERT INTO PRODUTO (NOME, VALOR, FK_CATEGORIA, IMAGEM) VALUES 
('INTENSIVE SERUM-TROPICAL RESINS SISLEY', 4480, 6, NULL),
('MARCARA FACIAL', 890, 6, NULL),
('CREME OLHEIRAS SISLEY', 1115, 6, NULL),
('SISLEY ANTI-AGE EXTRARICHE', 4350, 6, NULL);

-- Categoria: Hidratante (ID 3)
INSERT INTO PRODUTO (NOME, VALOR, FK_CATEGORIA, IMAGEM) VALUES 
('HIDRATANTE ANGEL', 499, 3, NULL),
('HIDRATANTE VS BARE VANILLA', 198, 3, NULL),
('DIOR PRESTIGE', 3439, 3, NULL),
('YSL LIBRE CREME CORPORAL', 389, 3, NULL);

-- Categoria: Perfume (ID 5)
INSERT INTO PRODUTO (NOME, VALOR, FK_CATEGORIA, IMAGEM) VALUES 
('LIBRE YSLEUA DE PARFUM', 937, 5, NULL),
('MARLY DELINA LA ROSÉE', 2000, 5, NULL),
('ROSE GOLDEA EUA DE PERFUM', 905, 5, NULL),
('ROJA DOVE DIAGHILEV', 10600, 5, NULL);
